### ISSUE TITLE
Unable to join when using Vanilla tweaks

### ISSUE THREAD

**Issue by LLjo** [TheIllusiveC4/CorpseComplex#41]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: corpsecomplex-FORGE-1.15.2-2.0-beta6
* Forge:1.15.2: 31.2.27
#### Steps to Reproduce: 
1. Have Vanilla tweaks and this mod installed on a server + client
2. more mods it doesn't work with but don't have time to test which one of them.

Crash Log: internal execption: java.lang.nullpointer.exception 

debug last lines:
[27Jun2020 13:03:32.917] [Netty Server IO #2/DEBUG] [net.minecraftforge.fml.network.FMLLoginWrapper/FMLHANDSHAKE]: Recieved login wrapper packet event for channel fml:handshake with index 32
[27Jun2020 13:03:32.917] [Netty Server IO #2/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Received client indexed reply 32 of type net.minecraftforge.fml.network.FMLHandshakeMessages$C2SAcknowledge
[27Jun2020 13:03:32.917] [Netty Server IO #2/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Received acknowledgement from client
[27Jun2020 13:03:32.917] [Server thread/DEBUG] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Sending ticking packet info 'Config behgameon-config.toml' to 'fml:handshake' sequence 34
[27Jun2020 13:03:32.971] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@449021fb[id=e0asd4ae5-8ccb-4ffe-9a7c-93484aafd6ed,name=afs,properties={textures=[com.mojang.authlib.properties.Property@4d97a5c2]},legacy=false] (/"ip") lost connection: Disconnected

**Comment by TheIllusiveC4** [comment]
Can you share your crash log? There's more information that comes with a `NullPointerException` that would help identify the cause.

**Comment by LLjo** [comment]
was no crash log but in the normal log here is something:

[15:46:27] [Render thread/INFO]: Connecting to 192-------------------
[15:46:30] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[15:46:30] [Netty Client IO #1/FATAL]: Forge config just got changed on the file system!
[15:46:30] [Netty Client IO #1/ERROR]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2122/2127940748@5b41e0a9
java.lang.NullPointerException
	at top.theillusivec4.corpsecomplex.common.config.ConfigParser.parseItems(ConfigParser.java:53)
	at top.theillusivec4.corpsecomplex.common.util.manager.DeathOverrideManager.lambda$importConfig$2(DeathOverrideManager.java:87)
	at top.theillusivec4.corpsecomplex.common.util.manager.DeathOverrideManager$$Lambda$11077/1962409833.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at top.theillusivec4.corpsecomplex.common.util.manager.DeathOverrideManager.importConfig(DeathOverrideManager.java:64)
	at top.theillusivec4.corpsecomplex.CorpseComplex.config(CorpseComplex.java:91)
	at top.theillusivec4.corpsecomplex.CorpseComplex$$Lambda$3033/908797909.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2122/2127940748.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:66)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2288/1009383102.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$5(ModContainer.java:147)
	at net.minecraftforge.fml.ModContainer$$Lambda$8809/646614683.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:147)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:89)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$receiveSyncedConfig$5(ConfigTracker.java:123)
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$11070/2071111322.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.config.ConfigTracker.receiveSyncedConfig(ConfigTracker.java:121)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.handleConfigSync(FMLHandshakeHandler.java:270)
	at net.minecraftforge.fml.network.NetworkInitialization$$Lambda$2166/296563327.accept(Unknown Source)
	at net.minecraftforge.fml.util.ThreeConsumer.lambda$bindArgs$0(ThreeConsumer.java:43)
	at net.minecraftforge.fml.util.ThreeConsumer$$Lambda$11030/1451894421.accept(Unknown Source)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.lambda$biConsumerFor$1(FMLHandshakeHandler.java:143)
	at net.minecraftforge.fml.network.FMLHandshakeHandler$$Lambda$2142/1885253670.accept(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$11029/734367928.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2120/2098233443.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2122/2127940748.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.network.NetworkInstance.dispatchLoginPacket(NetworkInstance.java:105)
	at net.minecraftforge.fml.network.FMLLoginWrapper.lambda$wrapperReceived$5(FMLLoginWrapper.java:69)
	at net.minecraftforge.fml.network.FMLLoginWrapper$$Lambda$11025/750864228.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.FMLLoginWrapper.wrapperReceived(FMLLoginWrapper.java:68)
	at net.minecraftforge.fml.network.FMLLoginWrapper$$Lambda$2140/857308207.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2122/2127940748.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78)
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$11017/1328714628.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78)
	at net.minecraft.client.network.login.ClientLoginNetHandler.func_209521_a(ClientLoginNetHandler.java:130)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:34)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:11)
	at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:149)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheIllusiveC4** [comment]
I think I know the cause of the issue. Did you change anything in the Corpse Complex configs from the defaults? Particularly `corpsecomplex-server.toml`. If you did, then could you share that file? If not, then you don't have to.
