### ISSUE TITLE
Unable to respawn with keepInventory enabled

### ISSUE THREAD

**Issue by Theta-Dev** [TheIllusiveC4/CorpseComplex#46]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 1.15.2-2.0-beta8
* Forge: 31.2.37
#### Observed Behavior:
When keepInventory is enabled and you die, you are not able to respawn. Clicking the respawn button produces a NullPointerException.
#### Expected Behavior:
Be able to respawn without triggering any of Corpse Complex's respawn events like losing/damaging items and xp.
#### Steps to Reproduce:
1. Set the gamerule keepInventory to true
2. Kill yourself
3. Click on the respawn button

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/3tJpfcEv

**Comment by Theta-Dev** [comment]
Thank you very much for the quick fix. Now I can put Corpse Complex back into my modpack.

**Comment by Theta-Dev** [comment]
Just did some more testing. In Vanilla the issue is fixed.
When adding Corpse Complex to my modpack however, the issue persists with Corpse Complex Beta 9 (1.15.2).
Upon further investigation it seems that the Curios integration is the culprit.

Using the Curios mod together with Corpse Complex creates the same error as mentioned above.

`[m[1;31m[22:42:17] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
	at top.theillusivec4.corpsecomplex.common.modules.inventory.inventories.integration.CuriosInventory.lambda$retrieveInventory$3(CuriosInventory.java:66) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at top.theillusivec4.corpsecomplex.common.modules.inventory.inventories.integration.CuriosInventory.retrieveInventory(CuriosInventory.java:65) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at top.theillusivec4.corpsecomplex.common.modules.inventory.InventoryModule.lambda$null$6(InventoryModule.java:102) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261] {}
	at top.theillusivec4.corpsecomplex.common.modules.inventory.InventoryModule.lambda$null$7(InventoryModule.java:102) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at top.theillusivec4.corpsecomplex.common.modules.inventory.InventoryModule.lambda$playerRespawn$8(InventoryModule.java:100) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at top.theillusivec4.corpsecomplex.common.modules.inventory.InventoryModule.playerRespawn(InventoryModule.java:99) ~[?:FORGE-1.15.2-2.0-beta9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3_InventoryModule_playerRespawn_Clone.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:474) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1015) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:408) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1104) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}`
